name: intellihire
description: "Intelligent Recruitment & Skill Assessment System"

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  animations: ^2.1.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  custom_refresh_indicator: ^4.0.1
  dynamic_color: ^1.8.1
  expressive_loading_indicator: ^0.0.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  heroine: ^0.5.0+2
  http: ^1.5.0
  image_picker: ^1.2.0
  material_symbols_icons: ^4.2874.0
  motor: ^1.0.1
  shared_preferences: ^2.5.3
  simple_icons: ^14.6.1
  skeletonizer: ^2.1.0+1

dependency_overrides:
  vector_math: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
